export const skills = {
    heading: "Skills",
    // quote: "''What we observe is not nature itself, but nature exposed to our method of questioning.''",
    techSkills: [
        "JavaScript",
        "NodeJS",
        "ReactJS",
        "React Native",
        "MongoDB",
        "Express",
        "MySQL",
        "Redux",
        "HTML",
        "CSS",
        "jQuery",
        "Bootstrap",
        "Git",
        "GitHub",
        "Version Control",
        "PHP Frameworks",
        "APIs, REST and SOAP",
        "UI/UX Design",
        "User Authentication",
        "Security and Session Storage",
        "Unit Test Writing",
        "Algorithms",
        "Data Structures",
    ],
    industryKnowledge: [
        "Software",
        "Marketing",
        "Publicity",
        "Social Media",
        "Content Writing",
        "Creative Writing",
        "Web Content",
        "Frontend",
        "Backend",
        "Design",
        "Abstraction",
        "Algorithms",
        "AI",
        "Machine Learning",
        "Data Science",
        
    ],
    interpersonalSkills: [
        "Management",
        "Leadership",
        "Empathy",
        "Compassion",
        "Honesty",
        "Joyfull Heart",
        "Adaptability",
        "Confidence",
        "Respect",
        "Communication",
        "Adaptability",
        "Confidence",
        "Respect",
        "Communication",
        "Collaboration",
        "Cooperation",
        "Self-management",
        "Time-management",
        "Analysis",
        "Logical Thinking",
        "Imagination",
        "Organization",
    ]
};